# Generated by Django 4.0.4 on 2022-05-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_choices',
            field=models.CharField(choices=[('11', 'Vegetation'), ('12', 'Trees'), ('13', 'Nature'), ('14', 'Fashion'), ('15', 'IT & Computers'), ('16', 'Animals'), ('17', 'Illustrations'), ('18', 'City'), ('19', 'Business'), ('20', 'Industries'), ('21', 'Objects'), ('22', 'Technology'), ('23', 'People'), ('24', 'Travel')], max_length=10),
        ),
    ]
