# Generated by Django 4.0.4 on 2022-05-31 21:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_image_title_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=cloudinary.models.CloudinaryField(default='DEFAULT VALUE', max_length=255, verbose_name='image'),
        ),
    ]
